name: Feature Request
description: Suggest a feature
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "Thanks for the suggestion!"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Why is this useful?
    validations:
      required: true
